name: JMeter Docker Test

on:
push:
branches:
-main

jobs:
build-and-test:
runs-on: ubuntu-latest

steps:
-name: Checkout repository
uses: actions/checkout@v2

-name: Set up Docker Buildx
uses: docker/setup-buildx-action@v1

-name: Build Docker image
run: docker build -t my-jmeter-image.

-name: Run JMeter Test
run: docker run my-jmeter-image
env:
USERNAME: ${{secrets.JMETER_USERNAME}}
PASSWORD: ${{secrets.JMETER_PASSWORD}}
