name: JMeter Performance Tests

on: workflow_dispatch
jobs:
  test:
    runs-on: [default-nonprod]

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run JMeter tests
      run: |
       docker login hub.docker.internal.cba -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
       docker run --rm --name jmeter -i -v "$(pwd)":/tmp -p 9270:9270 chiabre/jmeter_plugins:5.5-0.1.1 -t SampleAPITest_2mins.jmx
