name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      uses: actions/checkout@v2

    - name: Run JMeter tests
      run: |
       docker login hub.docker -u ${{JMETER_USERNAME }} -p ${{JMETER_PASSWORD }}
       docker run --name=jmeter -i -v ${PWD}:/jmeter hub.docker.internal.cba/justb4/jmeter -n -t /jmeter/SampleAPITest_2mins.jmx -l /jmeter/results.jtl
