name: JMeter Docker Test
on:
  push:
   branches:
    -main

jobs:
 build-and-test:
  runs-on: ubuntu-latest
  steps:
     - name: Check out code
       uses: actions/checkout@v2

     - name: Run JMeter tests
       run: |
        docker login hub.docker.internal.cba -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker run --name=jmeter -i -v ${PWD}:/jmeter hub.docker.internal.cba/justb4/jmeter -n -t /jmeter/SampleAPITest_2mins.jmx -l /jmeter/results.jtl
